version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - backend
  


  web:
    image: event-planner:${VERSION:-latest}
    #image: 006262944085.dkr.ecr.us-east-1.amazonaws.com/tova-portfolio/event-planner:v1.0.12
    container_name: event-planner
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI} #'mongodb://root:1234@mongo:27017/event_db?authSource=admin'
      FLASK_APP: 'app/app.py'
      FLASK_ENV: 'development'
    ports:
    - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - web
    networks:
      - frontend


volumes:
  mongo_data:

networks:
  backend:
  frontend:
