version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  


  web:
    image: event-planner:${VERSION:-latest}
    container_name: event-planner
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
      FLASK_APP: 'app/app.py'
      FLASK_ENV: 'development'
    ports:
    - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - web
    networks:
      - frontend


volumes:
  mongo_data:

networks:
  backend:
  frontend:
