name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main


env:
  AWS_REGION: 'us-east-1'
  ECR_REPO_EVENT_PLANNER: 'tova-portfolio/event-planner'
  IMAGE_TAG: 'latest'
  IMAGE_NAME: 'event-planner'
  AWS_ACCOUNT_ID: '006262944085' 
  ECR_URI: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com' 
  EC2_IP: 'localhost'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate_new_version.outputs.NEW_VERSION }}

    steps:
      # 1. Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Check for Merge Conflicts
      - name: Check for Merge Conflicts
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          git merge --no-commit --no-ff origin/main || echo "Merge conflicts detected!"

      - name: Set environment variable based on branch
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "release" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          else
            echo "ENV=development" >> $GITHUB_ENV
          fi

      # 3. Calculate new version if branch is main
      - name: Calculate new version
        id: calculate_new_version
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Fetching tags..."
          git fetch --tags
          latestTag=$(git tag --sort=-v:refname | head -1)
          echo "Latest tag fetched: $latestTag"
      
          if [[ "$latestTag" == "" ]]; then
            echo "No tags found, the tag will be v1.0.0"
            NEW_VERSION="v1.0.0"
          else
            echo "Existing tags found"
            currentNumber=$(echo $latestTag | grep -oP '\d+\.\d+\.(\d+)' | grep -oP '\d+$')
            echo "Extracted current number: $currentNumber"
            NEW_VERSION="v$(echo $latestTag | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2./')$((currentNumber + 1))"
          fi
      
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "The new version: $NEW_VERSION"

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$( [ "$GITHUB_REF" == "refs/heads/main" ] && echo $NEW_VERSION || echo $IMAGE_TAG ) .

      # 5. Run E2E tests
      - name: Run E2E tests
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker compose version
          docker-compose down
          VERSION=${{ env.NEW_VERSION }} MONGO_URI=${{ secrets.MONGO_URI }} MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} ENV=${{ env.ENV }} docker-compose up -d
          sleep 30
          chmod +x e2e_test.sh
          ./e2e_test.sh ${EC2_IP}
          docker-compose down
          sudo apt-get remove -y docker-compose      

      # 6. Publish version and push tag (only for main branch)
      - name: Publish version
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "tova.klein@develeap.com"
          git config --global user.name "tova.klein"
          git tag -a ${NEW_VERSION} -m "Version ${NEW_VERSION}"
          git push origin ${NEW_VERSION}

      # 7. Push the new image to the ECR docker registry
      - name: Push Docker Image to ECR
        if: github.ref == 'refs/heads/main'
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
          docker tag $IMAGE_NAME:${{ env.NEW_VERSION }} ${{ env.ECR_URI }}/${{ env.ECR_REPO_EVENT_PLANNER }}:${{ env.NEW_VERSION }}
          docker push ${{ env.ECR_URI }}/${{ env.ECR_REPO_EVENT_PLANNER }}:${{ env.NEW_VERSION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 8. Update GitOps repo with new image tag
      - name: Update image tag in GitOps repo
        if: github.ref == 'refs/heads/main'
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/KleinTova/portfolio-gitops-config.git
          cd portfolio-gitops-config

          sed -i "s/tag: \".*\"/tag: \"${NEW_VERSION}\"/" event-planner-umbrella-chart/charts/event-planner/values.yaml

          git config --global user.email "tova.klein@develeap.com"
          git config --global user.name "tova.klein"

          git add event-planner-umbrella-chart/charts/event-planner/values.yaml
          git commit -m "Update image tag to ${NEW_VERSION}"
          git push origin main
        env:
          GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}

  report:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Print success message if pipeline succeeds
        if: success()
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Pipeline succeeded. The new version is ${{ needs.build.outputs.version }}"
          else
            echo "Pipeline succeeded on feature branch."
          fi

      - name: Print failure message if pipeline fails
        if: failure()
        run: echo "Pipeline failed. Please check the logs and the issue in the build process."